### ISSUE TITLE
esphome name with lowercases in yaml file

### ISSUE THREAD

**Issue by bwaves** [thomasvnl/esphome-open-air-valve#2]
Some not about the page: https://github.com/thomasvnl/esphome-open-air-valve/blob/main/open-air-valve.yaml, that begin with:

esphome:
  name: "Open-AIR-Valve X"

in the github text is stated:
Change the "X" in open-air-valve.yaml with a number or a letter. This will help you identify the Open AIR Valves.

That X can be repaced is clear, but Home Asistant also give a error due the capital letters so it must replaced, but also the "O" in "Open". In het comment are lowercases used, but in the yaml is Open-AIR-Valve X is used (and maybe space).

**Comment by thomasvnl** [comment]
Thanks for reaching out. You seem to be right, as per the EPSHome documentation regarding naming the device. I will update the yaml accordingly in a sec.
